name: Deploy on pypi.org

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: latest

    - name: Build packages
      run: uv build

    - name: Publish on pypi.org
      uses: pypa/gh-action-pypi-publish@v1.12.4
